# Generated by Django 3.2.4 on 2021-07-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=3000)),
                ('image', models.ImageField(blank=True, upload_to='blog/images')),
            ],
        ),
    ]
